title: <p align="center"> Sajan Kedia </p>
logo: /assets/img/logo.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/shayan-banerjee-3b8415101/">LinkedIn</a> |
  <a href="https://github.com/ShayanBanerjee">GitHub</a>
  
  <br>
  As an AI engineer with half a decade of experience, I'm dedicated to pushing the boundaries of technology. 
  I aim to lead transformative projects, from concept to execution, leveraging cutting-edge AI solutions. 
  With a focus on collaboration and mentorship, I strive to drive innovation and deliver impactful results. 
  Equipped with a deep understanding of AI trends, I'm poised to make a significant mark in this dynamic field.
  <br>
  </p>



theme: jekyll-theme-minimal